/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5-dev */

#ifndef PB_PIDSETREQ_PB_H_INCLUDED
#define PB_PIDSETREQ_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PidSetReq {
    uint32_t requestId;
    double p;
    double i;
    double d;
} PidSetReq;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PidSetReq_init_default                   {0, 0, 0, 0}
#define PidSetReq_init_zero                      {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PidSetReq_requestId_tag                  1
#define PidSetReq_p_tag                          2
#define PidSetReq_i_tag                          3
#define PidSetReq_d_tag                          4

/* Struct field encoding specification for nanopb */
#define PidSetReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   requestId,         1) \
X(a, STATIC,   SINGULAR, DOUBLE,   p,                 2) \
X(a, STATIC,   SINGULAR, DOUBLE,   i,                 3) \
X(a, STATIC,   SINGULAR, DOUBLE,   d,                 4)
#define PidSetReq_CALLBACK NULL
#define PidSetReq_DEFAULT NULL

extern const pb_msgdesc_t PidSetReq_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PidSetReq_fields &PidSetReq_msg

/* Maximum encoded size of messages (where known) */
#define PidSetReq_size                           33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
